// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void SpawnCowHandler(ReducerEventContext ctx, SpawnCowTimer timer);
        public event SpawnCowHandler? OnSpawnCow;

        public void SpawnCow(SpawnCowTimer timer)
        {
            conn.InternalCallReducer(new Reducer.SpawnCow(timer), this.SetCallReducerFlags.SpawnCowFlags);
        }

        public bool InvokeSpawnCow(ReducerEventContext ctx, Reducer.SpawnCow args)
        {
            if (OnSpawnCow == null) return false;
            OnSpawnCow(
                ctx,
                args.Timer
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class SpawnCow : Reducer, IReducerArgs
        {
            [DataMember(Name = "_timer")]
            public SpawnCowTimer Timer;

            public SpawnCow(SpawnCowTimer Timer)
            {
                this.Timer = Timer;
            }

            public SpawnCow()
            {
                this.Timer = new();
            }

            string IReducerArgs.ReducerName => "spawn_cow";
        }
    }

    public sealed partial class SetReducerFlags
    {
        internal CallReducerFlags SpawnCowFlags;
        public void SpawnCow(CallReducerFlags flags) => SpawnCowFlags = flags;
    }
}
