// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class CowHandle : RemoteTableHandle<EventContext, Cow>
        {
            protected override string RemoteTableName => "cow";

            public sealed class EntityIdUniqueIndex : UniqueIndexBase<uint>
            {
                protected override uint GetKey(Cow row) => row.EntityId;

                public EntityIdUniqueIndex(CowHandle table) : base(table) { }
            }

            public readonly EntityIdUniqueIndex EntityId;

            internal CowHandle(DbConnection conn) : base(conn)
            {
                EntityId = new(this);
            }

            protected override object GetPrimaryKey(Cow row) => row.EntityId;
        }

        public readonly CowHandle Cow;
    }
}
