// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class SpawnCowTimerHandle : RemoteTableHandle<EventContext, SpawnCowTimer>
        {
            protected override string RemoteTableName => "spawn_cow_timer";

            public sealed class ScheduledIdUniqueIndex : UniqueIndexBase<ulong>
            {
                protected override ulong GetKey(SpawnCowTimer row) => row.ScheduledId;

                public ScheduledIdUniqueIndex(SpawnCowTimerHandle table) : base(table) { }
            }

            public readonly ScheduledIdUniqueIndex ScheduledId;

            internal SpawnCowTimerHandle(DbConnection conn) : base(conn)
            {
                ScheduledId = new(this);
            }

            protected override object GetPrimaryKey(SpawnCowTimer row) => row.ScheduledId;
        }

        public readonly SpawnCowTimerHandle SpawnCowTimer;
    }
}
