// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class UfoHandle : RemoteTableHandle<EventContext, Ufo>
        {
            protected override string RemoteTableName => "ufo";

            public sealed class EntityIdUniqueIndex : UniqueIndexBase<uint>
            {
                protected override uint GetKey(Ufo row) => row.EntityId;

                public EntityIdUniqueIndex(UfoHandle table) : base(table) { }
            }

            public readonly EntityIdUniqueIndex EntityId;

            public sealed class PlayerIdIndex : BTreeIndexBase<uint>
            {
                protected override uint GetKey(Ufo row) => row.PlayerId;

                public PlayerIdIndex(UfoHandle table) : base(table) { }
            }

            public readonly PlayerIdIndex PlayerId;

            internal UfoHandle(DbConnection conn) : base(conn)
            {
                EntityId = new(this);
                PlayerId = new(this);
            }

            protected override object GetPrimaryKey(Ufo row) => row.EntityId;
        }

        public readonly UfoHandle Ufo;
    }
}
