// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class Cow
    {
        [DataMember(Name = "entity_id")]
        public uint EntityId;
        [DataMember(Name = "direction")]
        public DbVector3 Direction;
        [DataMember(Name = "speed")]
        public float Speed;
        [DataMember(Name = "is_being_abducted")]
        public bool IsBeingAbducted;

        public Cow(
            uint EntityId,
            DbVector3 Direction,
            float Speed,
            bool IsBeingAbducted
        )
        {
            this.EntityId = EntityId;
            this.Direction = Direction;
            this.Speed = Speed;
            this.IsBeingAbducted = IsBeingAbducted;
        }

        public Cow()
        {
            this.Direction = new();
        }
    }
}
