// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class Ufo
    {
        [DataMember(Name = "entity_id")]
        public uint EntityId;
        [DataMember(Name = "player_id")]
        public uint PlayerId;
        [DataMember(Name = "direction")]
        public DbVector3 Direction;
        [DataMember(Name = "speed")]
        public float Speed;
        [DataMember(Name = "last_split_time")]
        public SpacetimeDB.Timestamp LastSplitTime;
        [DataMember(Name = "beam_on")]
        public bool BeamOn;
        [DataMember(Name = "abducting")]
        public bool Abducting;
        [DataMember(Name = "abducted_entity")]
        public Entity? AbductedEntity;

        public Ufo(
            uint EntityId,
            uint PlayerId,
            DbVector3 Direction,
            float Speed,
            SpacetimeDB.Timestamp LastSplitTime,
            bool BeamOn,
            bool Abducting,
            Entity? AbductedEntity
        )
        {
            this.EntityId = EntityId;
            this.PlayerId = PlayerId;
            this.Direction = Direction;
            this.Speed = Speed;
            this.LastSplitTime = LastSplitTime;
            this.BeamOn = BeamOn;
            this.Abducting = Abducting;
            this.AbductedEntity = AbductedEntity;
        }

        public Ufo()
        {
            this.Direction = new();
        }
    }
}
